# -*- coding: utf-8 -*-
"""Ass3CropRGBImage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hwz3hOENxUgpzJK2ChaoKkbThlW8zGsq
"""

#Crop an RGB image from every side by 1/4th of its’ actual size.
# Importing Image class from PIL module

import cv2 as cv
from google.colab.patches import cv2_imshow
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

img = Image.open("lionking.jpg")   # Opens this image in RGB mode

width, height = img.size # Size of original image

print(img.size) #print image width and height 

# Setting the points for cropped image

left = width/4
top = height / 4
right = width-(width/4)
bottom = height-(height/4)

img1 = img.crop((left, top, right, bottom)) # Cropped image from every side by 1/4th of its’ actual size

display(img) #showing original image 

display(img1) #showing cropped image